name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: mkdir ./tps
      
      - name: setup python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: '3.10'
      
      - name: remove profesors comments
        run: python script.py
     

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            tp1/tp1.tex
            tp2/tp2.tex
            tp3/tp3.tex
            tp4/tp4.tex
            tp5/tp5.tex
            tp6/tp6.tex
            tp7/tp7.tex
            tp8/tp8.tex
            tp9/tp9.tex
            tp10/tp10.tex
      - name: ls
        run: ls

          
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: www1.frm.utn.edu.ar
          username: franciscoiglesias
          password: ${{ secrets.ftp_password }}
          local-dir: ./tps/
          server-dir: /electronica/analisisdsys/assets/files/
